config/routes.rb
Rails.application.routes.draw do
  resources :users  
  resources :events


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def index
    @events = Event.all
  end
    
  def new
    @event = Event.new
  end
    
    
  def create
    #@event = Event.new(params[:id])
    @event = Event.new(event_params)
    #@event.user_id = params[:user_id]
  
    

    @event.save

    #redirect_to event_path(@event)
    #redirect_to event_path(params[@event.id])
    #redirect_to events_path

  end
  
  def edit
  end

  def show
    @event = Event.find(params[:id])
  end

  def index
    # @events = Event.paginate(page: params[:page]).per_page(10)
    #@events_upcoming = Event.upcoming.paginate(page: params[:upcoming])
    #@events_past = Event.past.paginate(page: params[:past])
  end

  private
    def event_params
      #params.require(:event).permit(:title, :location, :description, :date, :user)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<h3>Create an Event</h3>

app/views/events/index.html.erb
<h1>Browse All Events</h1>
<h1>Events </h1>

<ul id="events">
    <% Event.all.each do |event| %>
    <li>
      <%= event.title %>
      <% end %>
    </li>
</ul>

<h2>Upcoming</h2>


<h2>Past</h2>


<%= link_to "Create a New Event", new_event_path, class: "new_event" %> |
<%= link_to 'Back to Users', users_path %> 

app/views/events/new.html.erb
<h1>Create a New Event</h1>

<%= form_for(@event) do |f| %>
  <ul>
  <% @event.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </p>
  <p>
    <%= f.label :location %><br />
    <%= f.text_area :location %>
  </p>
  
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :user_id, "Event Creator" %><br />
    <%= f.text_field :user_id %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to "<< Back to Events List", events_path %>

app/views/events/show.html.erb
<h3>Event Information for Event #<%= Event.first.id %></h3>
    <ul>
        <li><%= Event.first.title %></li>
        <li><%= Event.first.location %></li>
        <li>Date:<%= Event.first.date %></li>
        <li>Event Owner:<%= Event.first.user.name %></li>
        
    </ul>
    
<%= link_to "<< Back to Events List", events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_event.html.erb
<div>
  <h4>Event created by:  <%= @user.name %></h4>

</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %> |
<%= link_to "Events List", events_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<h3>Event Listing</h3>
<%= render partial: 'users/event' %>

<%= render partial: 'events/form' %>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> |
<%= link_to 'Events', events_path(:id) %>